name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Executing user-flow CLI
        uses: push-based/user-flow-gh-action@v0.1.0